web:
    image: php:5.6-apache
    volumes:
        - ./htdocs/:/var/www/html/
    ports:
        - "8000:80"
    links:
        - db

db:
    image: mysql
    environment:
        MYSQL_ROOT_PASSWORD: you_should_change_this
    volumes:
        - db/:/docker-entrypoint-initdb.d/
    ports:
        - "3306:3306"
